In [1]:
from services.data_service import load_site_data, load_coef_prior_samples
from solvers.stan import _theta_reg_data, _prior_hyperparams, _gamma_reg_data
import numpy as np

Importing MCMC Module: mcmc_sampling_original.py


In [2]:
# Load sites' data
(
    zbar_2017,
    gamma_vals,
    z_2017,
    forestArea_2017_ha,
    theta_vals,
    gamma_coe_mean,
    theta_coe_mean,
    gamma_coe_vcov,
    theta_coe_vcov,
    theta_data,
    gamma_data,
) = load_site_data(
    10,
    norm_fac=1e11,
)

Data successfully loaded from '/Users/patriciohernandez/Projects/project-amazon/data/hmc/hmc_10SitesModel.csv'


In [3]:
theta_data

id   X1  historical_precip  historical_temp  I.historical_temp.2.  \
0     1  1.0           2.095212         0.088626              0.073522   
1     5  1.0           2.095212         0.088626              0.073522   
2     1  1.0           2.591289         0.712883              0.710237   
3     2  1.0           2.591289         0.712883              0.710237   
4     1  1.0           3.194936         0.001980             -0.013873   
..   ..  ...                ...              ...                   ...   
684  10  1.0          -1.054217        -2.585480             -2.513731   
685  10  1.0          -0.864571        -2.011909             -1.977942   
686  10  1.0          -0.777167        -2.638213             -2.562466   
687  10  1.0          -1.197694        -1.191957             -1.193837   
688  10  1.0          -1.205307        -0.086401             -0.102773   

          lat  I.lat.2.  cattleSlaughter_farmGatePrice_2017  distance  \
0    0.503463  0.487875                            0.040508  2.321377   
1    0.503463  0.487875                            0.040508  2.321377   
2    0.716406  0.709940                           -0.335162  1.400975   
3    0.716406  0.709940                           -0.335162  1.400975   
4    0.891029  0.893893                            0.044990  1.667578   
..        ...       ...                                 ...       ...   
684 -1.864649 -1.814553                            0.759371  0.153849   
685 -1.862048 -1.812194                            2.504136 -0.710554   
686 -1.711920 -1.675312                            1.662586 -0.282200   
687 -1.637727 -1.607211                            0.674618  0.575946   
688 -1.539261 -1.516365                           -1.941180  0.879240   

     zbar_2017_muni  log_cattleSlaughter_valuePerHa_2017  
0      4.556219e+05                                  NaN  
1      4.556219e+05                                  NaN  
2      1.181881e+06                             5.621129  
3      1.181881e+06                             5.621129  
4      5.606640e+06                                  NaN  
..              ...                                  ...  
684    2.018173e+05                             4.528641  
685    1.144672e+05                             4.839621  
686    1.287097e+06                             3.844629  
687    5.881073e+05                             4.531010  
688    5.656621e+05                             3.247560  

[689 rows x 11 columns]

In [4]:
y, X, N, K, G = _theta_reg_data(10, theta_data)

In [5]:
N

595

In [6]:
theta_vals.mean()

1.4494814682000001

In [7]:
np.exp(y).mean() / 45

2.0972504336488367

In [8]:
I, mu, a, b = _prior_hyperparams(y, X, "theta").values()

In [14]:
print(a,b)

297.5 141.72717203731645


In [9]:
sigma_sq = b/(a+1)
sigma_sq

0.4747978962724169

In [10]:
sigma_sq * I

array([[ 8.27139833e-04,  8.21144130e-05,  1.40581266e-03,
        -1.39090501e-03, -2.20266601e-03,  2.27135554e-03,
        -7.53983671e-06, -3.57759667e-05],
       [ 8.21144130e-05,  1.32675067e-03,  1.08105401e-03,
        -1.10019365e-03,  2.53072785e-03, -3.10067362e-03,
         7.95028730e-05, -1.28797402e-04],
       [ 1.40581266e-03,  1.08105401e-03,  2.63551026e+00,
        -2.63022063e+00, -4.88952562e-01,  4.77151432e-01,
        -5.85916555e-03, -1.13435874e-02],
       [-1.39090501e-03, -1.10019365e-03, -2.63022063e+00,
         2.62660718e+00,  4.76029363e-01, -4.65400813e-01,
         5.85514002e-03,  1.14861659e-02],
       [-2.20266601e-03,  2.53072785e-03, -4.88952562e-01,
         4.76029363e-01,  1.28890702e+00, -1.28446570e+00,
         2.04403854e-03, -8.43539629e-03],
       [ 2.27135554e-03, -3.10067362e-03,  4.77151432e-01,
        -4.65400813e-01, -1.28446570e+00,  1.28221227e+00,
        -1.63461359e-03,  8.69130099e-03],
       [-7.53983671e-06,  7.950287

In [11]:
theta_coe_vcov

array([[ 1.79043664e-03,  1.87102904e-04, -1.48954507e-02,
         1.52546877e-02,  4.05584286e-03, -3.76701887e-03,
        -9.97299922e-05, -4.52171254e-04],
       [ 1.87102904e-04,  2.58478267e-03,  1.57691018e-02,
        -1.58337216e-02, -7.93730800e-03,  7.12878346e-03,
         3.95607669e-04, -2.42256299e-04],
       [-1.48954507e-02,  1.57691018e-02,  4.39711383e+00,
        -4.43109344e+00, -5.36101206e-01,  5.46802535e-01,
         7.81808398e-03, -1.62201990e-02],
       [ 1.52546877e-02, -1.58337216e-02, -4.43109344e+00,
         4.46762113e+00,  5.46064992e-01, -5.58013862e-01,
        -7.86745320e-03,  1.62573827e-02],
       [ 4.05584286e-03, -7.93730800e-03, -5.36101206e-01,
         5.46064992e-01,  1.48226633e+00, -1.49854999e+00,
         2.96771534e-03, -1.90109051e-02],
       [-3.76701887e-03,  7.12878346e-03,  5.46802535e-01,
        -5.58013862e-01, -1.49854999e+00,  1.51756886e+00,
        -2.38160786e-03,  1.93709906e-02],
       [-9.97299922e-05,  3.956076

In [13]:
mu

array([ 4.11870522, -0.02850041,  1.81046664, -1.91772524,  3.58996459,
       -3.68196692,  0.47485082, -0.00917657])

In [12]:
theta_coe_mean

array([ 4.02969724, -0.1316433 ,  3.82608647, -3.98272491,  7.07181111,
       -7.18249889,  0.48786878, -0.0928385 ])