In [1]:
from services.data_service import load_site_data, load_coef_prior_samples
from solvers.stan import _theta_reg_data, _prior_hyperparams, _gamma_reg_data
import numpy as np

Importing MCMC Module: mcmc_sampling_original.py


In [2]:
# Load sites' data
(
    zbar_2017,
    gamma_vals,
    z_2017,
    forestArea_2017_ha,
    theta_vals,
    gamma_coe_mean,
    theta_coe_mean,
    gamma_coe_vcov,
    theta_coe_vcov,
    theta_data,
    gamma_data,
) = load_site_data(
    10,
    norm_fac=1e11,
)

Data successfully loaded from '/Users/patriciohernandez/Projects/project-amazon/data/hmc/hmc_10SitesModel.csv'


In [3]:
gamma_data

id   X1  log_historical_precip  log_historical_temp   log_lat   log_lon  \
0     1  1.0               1.903604             0.115122  0.537821 -2.088157   
1     5  1.0               1.903604             0.115122  0.537821 -2.088157   
2     1  1.0               2.255230             0.721277  0.738985 -1.748519   
3     2  1.0               2.255230             0.721277  0.738985 -1.748519   
4     1  1.0               2.654689             0.030049  0.902289 -2.098580   
..   ..  ...                    ...                  ...       ...       ...   
706  10  1.0              -0.750612            -2.680345 -1.700176  0.040666   
707  10  1.0              -0.940483            -0.019466 -1.362865  0.323129   
708  10  1.0              -1.275154            -1.166513 -1.620548  0.245313   
709  10  1.0              -1.285130            -0.056968 -1.515409  0.342336   
710  10  1.0              -1.000612             0.631055 -1.318796  0.367171   

     log_co2e_ha_2017  
0            6.402935  
1            6.402935  
2            6.280606  
3            6.280606  
4            6.351144  
..                ...  
706          5.858993  
707          5.757545  
708          5.722272  
709          5.731415  
710          5.160738  

[711 rows x 7 columns]

In [4]:
y, X, N, K, G = _gamma_reg_data(10, gamma_data)

In [5]:
N

689

In [6]:
gamma_vals.mean()

474.0467252100001

In [7]:
np.exp(y).mean()

429.7343465200875

## Analysing hyperparams

In [8]:
I, mu, a, b = _prior_hyperparams(y, X, "gamma").values()

In [15]:
sigma_sq = b/(a-1)
sigma_sq

0.10499534770803728

In [16]:
sigma_sq * I

array([[ 1.53802475e-04, -1.58620786e-05, -8.80908376e-07,
         1.11141602e-05,  1.79022300e-06],
       [-1.58620786e-05,  2.67575976e-04, -2.03824370e-05,
        -1.64147356e-04,  1.18780620e-04],
       [-8.80908376e-07, -2.03824370e-05,  3.36937879e-04,
        -2.21974630e-04, -4.42876008e-05],
       [ 1.11141602e-05, -1.64147356e-04, -2.21974630e-04,
         4.43123555e-04, -1.11231200e-04],
       [ 1.79022300e-06,  1.18780620e-04, -4.42876008e-05,
        -1.11231200e-04,  2.38505280e-04]])

In [11]:
gamma_coe_vcov

array([[ 6.45960900e-04, -8.95458333e-06,  1.93524177e-06,
         7.20064833e-06, -7.96378794e-06],
       [-8.95458333e-06,  1.03903375e-03, -6.84134156e-05,
        -6.25545205e-04,  3.94983085e-04],
       [ 1.93524177e-06, -6.84134156e-05,  1.34038367e-03,
        -8.23531225e-04, -2.38269168e-04],
       [ 7.20064833e-06, -6.25545205e-04, -8.23531225e-04,
         1.69585693e-03, -3.96914329e-04],
       [-7.96378794e-06,  3.94983085e-04, -2.38269168e-04,
        -3.96914329e-04,  9.37949385e-04]])

In [12]:
mu

array([ 5.95764264,  0.06420788, -0.14454559,  0.19182394, -0.28300003])

In [13]:
gamma_coe_mean

array([ 5.952861  ,  0.07886516, -0.14459172,  0.17961496, -0.29161171])